apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-exchange-pod
  labels:
    app: currency-exchange
  namespace: fazar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: currency-exchange
  template:
    metadata:
      labels:
        app: currency-exchange
    spec:
      containers:
      - name: currency-exchange
        image: fazarsn/currency-exchange:v1
        env:
        - name: RABBIT_URI
          value: amqp://rabbitmq-service.fazar.svc.cluster.local:5672
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: currency-exchange-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: currency-exchange
